# Generated by Django 4.2.9 on 2024-10-02 09:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-datetime_sent']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='room',
            name='code',
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='hi', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
