# Generated by Django 4.2.9 on 2024-10-02 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_message_options_rename_text_message_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='body',
        ),
    ]
