# Generated by Django 4.2.9 on 2024-10-07 12:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_message_message_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='avatar',
            field=cloudinary.models.CloudinaryField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
