# Generated by Django 4.2.9 on 2024-10-08 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_room_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userroom',
            name='unread_messaged',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
