# Generated by Django 4.2.9 on 2024-10-08 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userroom_unread_messaged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userroom',
            old_name='unread_messaged',
            new_name='unread_messages',
        ),
    ]
