# Generated by Django 4.2.9 on 2024-10-10 09:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_unread_messaged_userroom_unread_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
